import type { Quote } from "./quote";

export const quotes: readonly Quote[] = [
  {
    id: "epicteto-enquiridion-1",
    text: "Todo lo que hay en la naturaleza, o depende de nosotros, o no depende. Lo que depende de nosotros son nuestras opiniones, nuestras inclinaciones, nuestros deseos, nuestras repugnancias: en una palabra, todas nuestras acciones: lo que no depende son los cuerpos, los bienes, la reputación, las dignidades; en fin, todo aquello que no es obra nuestra.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "1",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-2",
    text: "Las cosas que dependen de nosotros son libres por su naturaleza: nada puede forzarlas, ni servirlas de obstáculo: las que no dependen, son débiles, esclavas, inciertas y extranjeras.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "2",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-3",
    text: "Acuérdate, pues, que si crees libre lo que es dependiente por su naturaleza: si miras lo que no está en tu poder como una cosa que te sea propia, encontrarás obstáculos a cada paso: te verás afligido, turbado: acusarás a los dioses y a los hombres: en vez que si tomas solamente por tuyo lo que es realmente tuyo, y por ajeno lo que a otro pertenece, no experimentarás jamás embarazo, ni obstáculo en tus acciones: no acusarás ni vituperarás a nadie: nada harás contra tu gusto: nadie podrá ofenderte: no tendrás enemigos; y nada desagradable te sucederá.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "3",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-5",
    text: "Así pues, a la vista de algún accidente desagradable, di al instante: tú no eres más que una imaginación, y de ningún modo lo que pareces. Sírvete después, para determinar su medida, de las reglas que has aprendido, sobre todo de la primera: examina si esta desgracia es del número de aquellas cosas que están o no están en nuestro poder; porque si es de la naturaleza de las que no dependen de nosotros, di atrevidamente entonces, que ella no te toca.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "5",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-6",
    text: "Acuérdate de que el fin de todo deseo, es el de obtener lo que se apetece, así como el fin de toda aversión, es el de evitar lo que la causa; y que el hombre es igualmente desgraciado, sea que el suceso realice sus temores, sea que no corresponda a sus deseos.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "6",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-8",
    text: "Antes de ejecutar, piensa lo que vas a hacer. Si vas al baño, represéntate lo que en él pasa ordinariamente: allí se arrojan agua, se empujan, se dicen injurias, y se roba. Tú te presentarás en él con más seguridad, si te dices: Yo quiero bañarme; pero quiero también conservar mi independencia, aguantando todo lo que me impone la naturaleza.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "8",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-9",
    text: "No son las cosas las que turban a los hombres, sino la opinión que de ellas forman. La muerte, por ejemplo, no es un mal; si lo fuera, habría parecido tal a Sócrates. La opinión que se forma de la muerte, es la que la hace tan espantosa. Luego, pues, que nos hallamos impedidos o turbados, no acusamos de ello sino a nosotros mismos; esto es, a nuestras preocupaciones.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "9",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-9-sabio",
    text: "Acusar a los otros de las propias desgracias, es el hecho de un ignorante: hacerlas caer sobre sí, es empezar a instruirse: no acusar a los otros, ni a sí mismo, es ser sabio.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "9",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-12",
    text: "No pidas que los sucesos se arreglen a tus deseos; sino, conforma tus deseos a los sucesos: este es el medio de ser dichoso.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "12",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-13",
    text: "La enfermedad es un obstáculo para el cuerpo; pero no para la voluntad, a menos que esta no consienta en ello: tú eres cojo: ve ahí un obstáculo para tu pie; pero tu espíritu no deja por eso de estar libre. Si haces el mismo raciocinio sobre todos los demás accidentes de la vida, hallarás que siempre son un obstáculo para alguna otra cosa, y no para ti.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "13",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-14",
    text: "A cada impresión que recibas de los objetos exteriores, entra en ti mismo, y busca la facultad que para resistirlos te ha dado la naturaleza. Si ves un hermoso joven, o una joven bella, encontrarás en ti la continencia para defenderte de la seducción: contra la pena o el trabajo, hallarás el valor; y contra las injurias, la paciencia.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "14",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-11",
    text: "Jamás te ensoberbezcas con ninguna ventaja que no es tuya. Si un caballo dijera, alabándose, yo soy hermoso, se le podría sufrir; pero tú, cuando te glorías de tener un hermoso caballo, sabe que de esto te jactas. Ahora, ¿qué hay en esto que te pertenezca? El uso solo de tu imaginación. Por lo cual, si sabes arreglarla conforme a la naturaleza, entonces podrás gloriarte, porque a lo menos, te aplaudirás del bien, que es verdaderamente tuyo.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "11",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-32",
    text: "Cuando el esclavo de tu vecino ha roto un vaso u otra cosa, no dejas de decirle, que eso es una cosa que sucede muy a menudo, solo por consolarlo. Muestra, pues, la misma tranquilidad, si al tuyo le sucede lo mismo. Apliquemos esta máxima a objetos más serios. Si alguno pierde la mujer o el hijo, no hay nadie que no le diga, que esa es la suerte de la humanidad; pero si nosotros nos hallamos en el mismo caso, nos desesperamos.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "32",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-33",
    text: "Como jamás nos proponemos tal o tal cosa para que nos salga mal: del mismo modo la naturaleza del mal no existe en el mundo.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "33",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-34",
    text: "Si alguno entregara tu cuerpo a la discreción del primero que llegara, te indignarías sin duda; pero no te avergüenzas de abandonar tu alma, permitiendo al primero que llega, y te llena de injurias, que la turbe y la aflija a su gusto.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "34",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-35",
    text: "Nada hagas sin considerar primero lo que debe preceder, y lo que debe seguirse a la acción que proyectas.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "35",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-49",
    text: "Si te cuentan que han hablado mal de ti, no te entretengas en justificarte, y responde solamente: Ese tal no ha conocido mis demás defectos, porque entonces habría hablado mucho peor de mí.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "49",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-4",
    text: "Si aspiras en efecto a un fin tan noble, acuérdate, de que para conseguirlo, no debe desearse débilmente; sino que debes renunciar enteramente ciertas cosas: abstenerte por algún tiempo de algunas otras; y sobre todo, velar sobre ti mismo.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "4",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-7",
    text: "Examina con atención la cualidad de cada una de las cosas que contribuyen a tus placeres, que sirven para tus necesidades, o que tú amas; y comienza por las más viles. Si quieres una olla, di que quieres una olla; porque si se rompe, no te turbarás. Si amas a tu hijo o a tu mujer, acuérdate de que son mortales y si la muerte te los arrebata, no te alterarás.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "7",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-48",
    text: "Abstente, en cuanto sea posible, de los placeres del amor, antes de casarte: si los disfrutas, que sea según la ley. Pero no juzgues con demasiada severidad a aquellos que sobre este punto tienen principios menos severos; no los reprendas agriamente, y no publiques, ni te alabes a todo momento de tu continencia.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "48",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-11-barco",
    text: "Así como en un viaje de mar, si el barco arriba a un puerto, tú puedes bajar a tierra para hacer agua, y puedes también recoger algunas plantas y mariscos que se encuentran en la ruta; pero pensando siempre en tu barco, volviendo a él a menudo la cabeza para estar pronto cuando el patrón te llame: del mismo modo en el viaje de la vida, si en vez de un marisco o de una seta, te se da una mujer o un niño, puedes aceptarlos; pero si el patrón te llama, corre prontamente, y abandónalo todo sin mirar atrás.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "11",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "marco-aurelio-meditaciones-2-1",
    text: "Por la mañana no dejes de hacerte esta cuenta diciendo: tropezaré hoy con algún curioso, con algún ingrato, con algún provocativo, con otro doloso, con otro envidioso, con otro intratable; todos estos vicios les vienen a ellos de la ignorancia del bien y del mal. Pero yo, que por una parte tengo bien visto y meditado, que la naturaleza del bien totalmente consiste en lo honesto; la del mal en lo torpe, y que por otra conozco a fondo ser tal la condición del que peca, que no deja de ser mi pariente, no por un vínculo común de una misma sangre o prosapia, sino porque participamos de una misma mente y partícula, o porción divina; bien sé que ninguno de estos puede perjudicarme; ni debo enojarme contra quien es mi pariente, ni concebir odio contra su persona.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "2.1",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-2-2",
    text: "Todo mi ser consiste en una porción de carne, espíritu y mente que es la parte principal. Déjate ya, pues, de libros; no te distraigas por más tiempo. ¿No tienes en tu mano hacer cuanto te digo? Tú, como quien en breve ha de morir, desprecia tu cuerpecillo, que no es otro que una crasa sangre, unos huesecillos y un tejidillo de nervios, de pequeñas venas y de arterias.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "2.2",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-2-3",
    text: "Las obras de los dioses se dejan ver llenas de providencia; las de la fortuna, o tienen su origen en la misma naturaleza o no suceden sin concierto y conexión con aquellos efectos, a los cuales rige y preside la providencia, de la cual todo dimana.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "2.3",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-2-2-viejo",
    text: "Hazte así la cuenta, viejo eres, no permitas más que el alma de suyo señora se esclavice, ni que sea agitada a manera de títere con el ímpetu de las pasiones contrarias a la sociedad; no te desazonen las presentes disposiciones del hado, ni las futuras te asusten.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "2.2",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-2-14",
    text: "Por más que tú hubieses de vivir tres mil años, y, si quieres, aun treinta mil, con todo, haz por acordarte que ninguno pierde otra vida, al morir, que esta con que vive, ni vive con otra que con esta que pierde; así que, lo más largo y lo más breve de la vida, viene, al cabo, a reducirse a lo mismo; porque, para todos es igual aquel momento presente en que se vive.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "2.14",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-4-1",
    text: "El espíritu que en el hombre domina, cuando va bien concertado con la naturaleza, se halla en tal estado respecto a los acontecimientos, que siempre puede aplicarse con facilidad a lo que en el lance se le permite y propone como practicable; porque no se ata ni prefiere a materia alguna en particular, sino que de suyo se propone lo mejor, aunque siempre con la debida excepción, si se pudiere; y así cualquier estorbo que le sobreviniere hace de él y lo mira como materia y ejercicio de virtud.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "4.1",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-4-3",
    text: "Muchos para su retiro buscan las casas de campo, las orillas del mar, los montes; cosas que tú mismo solías desear con anhelo; pero todo esto es una vulgaridad, teniendo uno en su mano el recogerse en su interior y retirarse dentro de sí en la hora que le diere la gana; porque en ninguna parte tiene el hombre un retiro más quieto ni más desocupado que dentro de su mismo espíritu.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "4.3",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-4-3-tranquilidad",
    text: "La que yo ahora llamo tranquilidad no es otra cosa que un ánimo bien dispuesto y ordenado. Date, pues, de continuo a este retiro, y rehazte de nuevo en él.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "4.3",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-5-1",
    text: "Por la mañana, cuando sintieses pereza al levantarte, ten luego a mano esta reflexión: «Yo me levanto para cumplir con los oficios propios de un hombre». ¿Y qué, aun sea yo moroso, si voy a ejecutar aquello para que nací y para lo que vine al mundo? ¿O por ventura he sido yo formado para que rellanado en cama y envuelto entre cobertores me esté aquí calentando y solazando?",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "5.1",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-5-6",
    text: "Hecho su carrera el perro, seguido su caza, y la abeja trabajado la miel, así el hombre, que hizo bien a otro, no debe andar publicándolo, sino pensar solamente cómo podrá servirle otra vez, imitando en esto a la vid, que a su tiempo vuelve a llevar la uva.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "5.6",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-6-1",
    text: "La materia del universo se rinde y se dispone con facilidad; la mente, que la rige y modera, de ningún modo es en sí maléfica, puesto que no es maligna ni propensa a dañar a otro, ni capaz de recibir agravio de nadie. En el mundo se ejecuta todo y se lleva al cabo, como ella lo ordena.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "6.1",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-6-2",
    text: "Lo mismo se es el que tú cumplas con tu deber yerto de frío o bien abrigado, falto de sueño o harto de dormir, murmurado o alabado, muriendo o haciendo otra cualquiera cosa, porque también es una de las acciones del vivir la que ejecutamos muriendo, pues basta que cerca de esta dispongamos bien lo que entonces tuviéremos entre manos.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "6.2",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-6-54",
    text: "Lo que no es bueno para el enjambre, tampoco es conducente para la abeja.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "6.54",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-7-1",
    text: "¿Qué viene a ser la perversidad? es lo que has visto muchas veces: y así en todo acontecimiento ten a la mano esta reflexión, esto es lo que viste en varias ocasiones. Absolutamente desde el principio al fin hallarás los mismos sucesos, de los cuales están llenas las historias antiguas, las de la Edad Media y las de nuestros días; nada encontrarás de nuevo, todo es cosa trillada y de breve duración.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "7.1",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-7-2",
    text: "De ti pende el avivarlas de continuo. Yo puedo formar sobre este y el otro punto el debido juicio; y si puedo, ¿por qué me turbo? nada absolutamente tiene que ver con mi mente lo que está fuera de ella. Mantente en esta disposición y todo te irá bien. Tienes en tu mano el revivir, volviendo sobre ti; mira otra vez las cosas con los mismos ojos con que antes las viste, porque en esto consiste el revivir y recuperarse un hombre.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "7.2",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-4-48",
    text: "Procura, pues, pasar este punto indivisible de tiempo conformándote con la naturaleza y muriendo consolado, al modo que cuando la aceituna, estando ya madura, de suyo suele caerse, como que bendice a la Naturaleza que la crió, y que da las gracias al árbol que la produjo.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "4.48",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-8-2",
    text: "Yo consto de cuerpo y de alma: al cuerpecito, pues, todo le es indiferente, porque no puede discernir nada; al alma también es indiferente todo aquello que no sea acción suya peculiar, pero penden de su arbitrio todas sus obras particulares.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "8.2",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "seneca-cartas-1-tiempo",
    text: "De tal manera debes obrar, querido Lucilio, que seas dueño de ti mismo, y recoge y conserva el tiempo que acostumbran arrebatarte, sustraerte, o que dejas perder. Persuádete de que te escribo cosas ciertas: nos arrebatan parte del tiempo, nos lo sustraen o la dejamos perder. La peor de todas estas pérdidas es la que ocurre por negligencia propia.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "1",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-1-presente",
    text: "Haz, pues, querido Lucilio, lo que me escribes que haces; emplea bien todas las horas, y menos necesitarás del porvenir, cuanto mejor trabajes en el presente. Mientras nos detenemos, transcurre el tiempo. Todas las cosas nos son ajenas, querido Lucilio; solamente es nuestro el tiempo.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "1",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-2-ninguna",
    text: "Conviene detenerse y nutrirse de ciertos ingenios si queremos obtener de ellos algo que se adhiera sólidamente a nuestro ánimo. El que está en todas partes, no está en ninguna. Los que viajan sin cesar, tienen muchos huéspedes y ningún amigo.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "2",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-2-pobre",
    text: "No es pobre el que tiene poco, sino el que desea más de lo que tiene.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "2",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-5-esperar",
    text: "Cesarás de temer, dice, si cesas de esperar. Me dirás: ¿Cómo pueden reunirse cosas tan diversas? Ya lo ves, querido Lucilio; aunque parecen separadas, encuéntranse reunidas. Así como la misma cadena reúne al cautivo y al soldado que lo guarda, así dos cosas que parecen tan diferentes caminan a la par. El temor sigue a la esperanza.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "5",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-5-filosofia",
    text: "Procuremos que nuestro exterior esté conforme con el pueblo y que el interior no se le parezca en nada. Procuremos solamente que nuestra vida sea mejor, pero no distinta de la del vulgo.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "5",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-7-multitud",
    text: "Me preguntas qué es lo que principalmente debes evitar. La multitud. En ella no te encontrarás seguro. Confieso mi debilidad. Nunca salgo como entré en ella; despierta algo de lo que tenía adormecido, vuelve algún pensamiento que había desterrado.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "7",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-9-ama",
    text: "Hecatón dice: «Te revelaré un secreto que hará que te amen sin hierbas ni sortilegios: Ama si quieres que te amen.» Grande placer es contraer nuevas amistades y gozar de las antiguas.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "9",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-9-sabio",
    text: "El sabio está contento consigo mismo, no porque no quiera tener amigos, sino porque le basta poder tenerlos; y al decir poder tenerlos, entiendo que sufre sin emoción la pérdida de un amigo, porque nunca estará sin amigo, ya que en su poder está reparar en seguida esta pérdida.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "9",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-12-vivido",
    text: "He vivido. Recorrí la carrera que me deparó la fortuna. Si Dios da el día siguiente, recibámosle con alegría; aquel es feliz y sabe gozar de la vida, que espera el mañana sin inquietud. El que dice he vivido, diariamente gana.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "12",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-13-miedo",
    text: "Existen muchas más cosas, querido Lucilio, que nos causan miedo, que cosas que nos hacen daño, y muchas más veces estamos malos de aprensión que en realidad.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "13",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-13-prematuro",
    text: "Solamente te aconsejo que no padezcas prematuramente, porque lo que temes como muy cercano, tal vez no llegará jamás; y por lo menos es cierto que no ha llegado aún. Existen cosas que nos atormentan más de lo que deben, y otras que nos atormentan sin que deban atormentarnos. Aumentamos nuestro mal, lo hacemos o lo prevenimos.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "13",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-16-timon",
    text: "La filosofía forma el espíritu, ordena la vida, regula las acciones, muestra lo que se debe hacer y lo que se debe evitar, emplea el timón y dirige la nave en los pasos peligrosos. Sin ella, nadie está seguro.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "16",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-16-destino",
    text: "Ora nos ligue el destino con inmutable necesidad, ora Dios, como árbitro del universo, ordene todas las cosas, ora el acaso lleve y guíe ciegamente todos los actos humanos, es cosa cierta que la filosofía nos ayudará siempre; nos exhortará para que nos sometamos voluntariamente a Dios, para resistir constantemente la fortuna, para seguir los mandatos de la Providencia y para soportar los golpes del acaso.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "16",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-17-pobreza",
    text: "A muchos que querían dedicarse a la filosofía se lo han impedido las riquezas: la pobreza, por el contrario, siempre es libre y tranquila. Satisfacer el hambre cuesta poco, pero cuesta mucho satisfacer la inapetencia.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "17",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-34-bondad",
    text: "En las obras del espíritu sucede como en las demás, que se tienen medio terminadas cuando se han comenzado bien: por esta razón es mucha parte de bondad querer ser bueno.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "34",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-71-puerto",
    text: "Nuestros consejos se extravían porque no tienen objeto cierto, y no hay viento bueno, cuando no se sabe a qué puerto se quiere llegar. Mucho imperio, en verdad, ha de tener el azar en nuestra conducta, puesto que vivimos a la aventura.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "71",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-71-honesto",
    text: "El sumo bien es lo que es honesto, y lo que te admirará más: Un solo bien existe, lo que es honesto, los demás son bienes falsos y bastardos.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "71",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-78-vivir",
    text: "Esto me hizo consentir en continuar viviendo, porque algunas veces se necesita valor para tal resolución.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "78",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-98-animo",
    text: "El ánimo que se inquieta por lo porvenir, es desgraciado; nunca gozará de reposo, y el temor del mal futuro le hará perder el goce del bien presente. Igual es temer la pérdida de una cosa que el temor de perderla.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "98",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-98-fortuna",
    text: "Yerran aquellos, querido Lucilio, que creen que la fortuna da algo bueno o malo: da la materia para lo bueno o lo malo, y nosotros podemos hacer las cosas buenas o malas. El alma es más poderosa que la fortuna.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "98",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-123-desear",
    text: "Nadie puede tener lo que desea, pero todo el mundo puede dejar de desear lo que no tiene y recibir alegremente lo que se presenta.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "123",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-123-poco",
    text: "Necesario es acostumbrarse a contentarse con poco. Muchas dificultades de tiempo y lugar impiden a veces a los grandes, por bien provistos que estén, comer a la hora ordinaria.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "123",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-brevedad-1",
    text: "El tiempo que tenemos no es corto; pero perdiendo mucho de él, hacemos que lo sea, y la vida es suficientemente larga para ejecutar en ella cosas grandes, si la empleáremos bien. Lo cierto es que la vida que se nos dio no es breve, nosotros hacemos que lo sea; y que no somos pobres, sino pródigos del tiempo.",
    author: "Séneca",
    work: "Sobre la brevedad de la vida",
    locator: "1",
    source: {
      translator: "Pedro Fernández Navarrete",
      edition: "Tratados filosóficos, Tomo I, Biblioteca Clásica LXVII, Madrid, Luis Navarro (reimpresión Perlado Páez y Ca., Sucesores de Hernando, 1908)",
      year: 1884,
      url: "https://archive.org/details/tratadosfilosfi00navagoog",
    },
  },
  {
    id: "seneca-brevedad-2",
    text: "Larga es la vida, si la sabemos aprovechar. Pequeña parte de vida es la que vivimos: porque lo demás es espacio, y no vida, sino tiempo.",
    author: "Séneca",
    work: "Sobre la brevedad de la vida",
    locator: "2",
    source: {
      translator: "Pedro Fernández Navarrete",
      edition: "Tratados filosóficos, Tomo I, Biblioteca Clásica LXVII, Madrid, Luis Navarro (reimpresión Perlado Páez y Ca., Sucesores de Hernando, 1908)",
      year: 1884,
      url: "https://archive.org/details/tratadosfilosfi00navagoog",
    },
  },
  {
    id: "seneca-brevedad-3",
    text: "Teméis como mortales todas las cosas, y como inmortales las deseáis.",
    author: "Séneca",
    work: "Sobre la brevedad de la vida",
    locator: "3",
    source: {
      translator: "Pedro Fernández Navarrete",
      edition: "Tratados filosóficos, Tomo I, Biblioteca Clásica LXVII, Madrid, Luis Navarro (reimpresión Perlado Páez y Ca., Sucesores de Hernando, 1908)",
      year: 1884,
      url: "https://archive.org/details/tratadosfilosfi00navagoog",
    },
  },
  {
    id: "seneca-brevedad-4",
    text: "¿Cuál, pues, es la causa de esto? El vivir como si hubiérades de vivir para siempre, sin que vuestra fragilidad os despierte. No observáis el tiempo que se os ha pasado, y así gastáis de él como de caudal colmado y abundante, siendo contingente que el día que tenéis determinado para alguna acción sea el último de vuestra vida.",
    author: "Séneca",
    work: "Sobre la brevedad de la vida",
    locator: "4",
    source: {
      translator: "Pedro Fernández Navarrete",
      edition: "Tratados filosóficos, Tomo I, Biblioteca Clásica LXVII, Madrid, Luis Navarro (reimpresión Perlado Páez y Ca., Sucesores de Hernando, 1908)",
      year: 1884,
      url: "https://archive.org/details/tratadosfilosfi00navagoog",
    },
  },
  {
    id: "seneca-providencia-1",
    text: "Pregúntasme, Lucilo, cómo se compadece que gobernándose el mundo con divina Providencia, sucedan muchos males a los hombres buenos. Daréte razón de esto con más comodidad en el contexto del libro, cuando probare que a todas las cosas preside la Providencia divina, y que nos asiste Dios.",
    author: "Séneca",
    work: "Sobre la providencia",
    locator: "1",
    source: {
      translator: "Pedro Fernández Navarrete",
      edition: "Tratados filosóficos, Tomo I, Biblioteca Clásica LXVII, Madrid, Luis Navarro (reimpresión Perlado Páez y Ca., Sucesores de Hernando, 1908)",
      year: 1884,
      url: "https://archive.org/details/tratadosfilosfi00navagoog",
    },
  },
  {
    id: "epicteto-enquiridion-18",
    text: "Si deseas que tus hijos, tu mujer y tus amigos vivan eternamente, eres un loco; porque es querer, que las cosas que no dependen de ti, dependan, y que te pertenezca lo que es de otro.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "18",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-19",
    text: "Nuestro dueño es aquel que tiene el poder de arrebatarnos lo que queremos, y de que hagamos por fuerza lo que nos repugna. ¿Quieres ser libre? pues ni busques, ni huyas nada de lo que a otros pertenece: si no, serás necesariamente esclavo.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "19",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-20",
    text: "Acuérdate de portarte en la vida como en un festín. Si alargan un plato hacia ti, extiende la mano, y tómalo modestamente: si lo alejan, no lo retengas: si no viene por tu lado, no hagas conocer de lejos que lo deseas; sino espera con paciencia.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "20",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "marco-aurelio-meditaciones-8-1",
    text: "Sirve también para que no tengas vanidad el que en adelante no te puedes lisonjear de haber pasado filosóficamente toda la vida, o por lo menos la que medió desde tu juventud hasta ahora; antes bien, has estado muy lejos de la Filosofía, como no ignoran otros muchos y a ti te es bien claro. Ahora bien, si es que verdaderamente has conocido en qué consiste la vida filosófica, despreciando toda apariencia, conténtate con que vivas todo el tiempo que te queda, sea el que se fuere, según te dicte tu naturaleza.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "8.1",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-4-49-promontorio",
    text: "Haz por ser semejante a un promontorio contra quien las olas de la mar se estrellan de continuo y él se mantiene inmóvil, mientras que ellas hinchadas caen y se adormecen alrededor.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "4.49",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "seneca-cartas-21-practica",
    text: "Mejor sabes alabar la virtud que practicarla; ves claramente dónde reside la felicidad, pero no tienes valor para encaminarte a ella. Estimas en mucho lo que tendrías que abandonar, y al mismo tiempo que te representas la tranquilidad de que gozarías, te detiene sin duda el brillo de la vida que dejar.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "21",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-45-libros",
    text: "Te quejas de no tener bastantes libros. Más importa tenerlos buenos que tener muchos; porque la lectura de un libro especial es provechosa, y la de muchos solamente agradable. El que quiere llegar al fin que se propone debe seguir un camino solo y no emprender muchos, porque esto antes sería extraviarse que adelantar.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "45",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-75-cartas",
    text: "Te escribo lo mismo que te hablaría si nos encontrásemos sentados o paseando; con descuido y sencillamente, deseando que mis cartas no tengan nada rebuscado ni fingido. A ser posible, preferiría mostrarte mis sentimientos, a comunicártelos por escrito.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "75",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "seneca-cartas-90-vida",
    text: "¿Quién puede dudar, querido Lucilio, que la vida sea un don de los Dioses inmortales y que la vida virtuosa sea un favor de la filosofía? Lo más precioso y magnífico en ella es que no procede de la casualidad.",
    author: "Séneca",
    work: "Cartas a Lucilio",
    locator: "90",
    source: {
      translator: "Francisco Navarro y Calvo",
      edition: "Epístolas morales, Biblioteca Clásica LXVI, Madrid, Luis Navarro",
      year: 1884,
      url: "https://es.wikisource.org/wiki/Archivo:Ep%C3%ADstolas_morales_-_bdh0000051763.pdf",
    },
  },
  {
    id: "epicteto-enquiridion-21",
    text: "Si ves a alguno afligido, y llorando la pérdida de su fortuna, la muerte, o la ausencia de su hijo, ten cuidado de que no te engañe tu imaginación, y vayas a creer, que este hombre es desgraciado por la privación de estos bienes exteriores: entra al instante dentro de ti mismo, y haz esta distinción: Esta desgracia no es la que aflige a este hombre, supuesto que ella no mueve a otro; luego es la opinión que él tiene de ella la que le aflige.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "21",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-22",
    text: "Ten presente que estás en el mundo, como en un teatro, para representar en él el papel que el dueño te señale. Que sea corto o sea largo, poco importa. Si aquel quiere que hagas el de pobre, procura representar bien este personaje. Haz lo mismo, sea el que fuere el que te encargue, ya de un cojo, ya de un príncipe, o de un simple particular; porque a ti toca desempeñar bien el papel que te se da, y a otro el escogerlo.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "22",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-23",
    text: "Si el graznido de un cuervo presagia algunas desgracias, no se turbe por eso tu imaginación, haz al instante este razonamiento, y di: Ninguno de estos contratiempos me toca, si no antes a este cuerpo vil, a mi caudal, a mi reputación, a mis hijos o a mi mujer; pero por lo que hace a mí, no hay nada que no me anuncie mi felicidad, si yo lo quiero; porque sean los que fueren los sucesos, en mí está el sacar de ellos un gran partido.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "23",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-24",
    text: "¿Quieres ser invencible? pues no te expongas jamás a un combate, en el cual no veas que has de lograr la victoria.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "24",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-25",
    text: "Si ves a un hombre colmado de honores, o elevado a un gran poder, o bien distinguido con alguna otra ventaja, no te dejes deslumbrar de esas vanas apariencias, ni digas que es feliz; porque si la perfecta dicha y el reposo del espíritu consisten en las cosas que dependen de nosotros, los bienes extraños no deben hacernos envidiosos ni celosos.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "25",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "epicteto-enquiridion-26",
    text: "No olvides que la ofensa no está, ni en el insulto, ni en los golpes que recibes, sino en tu opinión. Luego, pues, que alguno exalta tu cólera, sabe que ese hombre no es quien te irrita, sino la opinión que has formado de él.",
    author: "Epicteto",
    work: "Enquiridión",
    locator: "26",
    source: {
      translator: "Enrique Ataide y Portugal",
      edition: "Manual de Epicteto, Madrid, Oficina de Aznar",
      year: 1802,
      url: "https://archive.org/details/BRes111594",
    },
  },
  {
    id: "seneca-bienaventurada-1",
    text: "Todos, oh hermano Galión, desean vivir bienaventuradamente; pero andan a ciegas en el conocimiento de aquello que hace bienaventurada la vida; y en tanto grado no es fácil el llegar a conocer cuál lo sea, que al que más apresuradamente caminare, desviándose de la verdadera senda y siguiendo la contraria, le vendrá a ser su misma diligencia causa de mayor apartamiento.",
    author: "Séneca",
    work: "Sobre la vida bienaventurada",
    locator: "1",
    source: {
      translator: "Pedro Fernández Navarrete",
      edition: "Tratados filosóficos, Tomo I, Biblioteca Clásica LXVII, Madrid, Luis Navarro (reimpresión Perlado Páez y Ca., Sucesores de Hernando, 1908)",
      year: 1884,
      url: "https://archive.org/details/tratadosfilosfi00navagoog",
    },
  },
  {
    id: "seneca-tranquilidad-1",
    text: "Haciendo de mí examen, en mí, oh amigo Sereno, se manifestaron unos vicios tan descubiertos que casi se podían cortar con la mano, y otros más escondidos y no continuados, sino que a ciertos intervalos volvían; y a éstos los tengo por molestísimos, porque, como enemigos vagos, asaltan en las ocasiones, sin dar lugar a estar prevenidos como en tiempo de guerra, ni descuidados como en la paz.",
    author: "Séneca",
    work: "Sobre la tranquilidad del ánimo",
    locator: "1",
    source: {
      translator: "Pedro Fernández Navarrete",
      edition: "Tratados filosóficos, Tomo I, Biblioteca Clásica LXVII, Madrid, Luis Navarro (reimpresión Perlado Páez y Ca., Sucesores de Hernando, 1908)",
      year: 1884,
      url: "https://archive.org/details/tratadosfilosfi00navagoog",
    },
  },
  {
    id: "marco-aurelio-meditaciones-4-49-dicha",
    text: "¡Infeliz de mí, dice uno, porque tal cosa me aconteció! En verdad no tiene razón: diría mejor: Dichoso yo, que en medio de lo que me sucedió, quedé sin recibir pena alguna; ni me quebranta lo presente, ni me espanta lo venidero; porque una semejante desgracia a todos pudo acontecer; pero no todos sin pena la hubieran podido llevar.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "4.49",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
  {
    id: "marco-aurelio-meditaciones-7-2-fuera",
    text: "nada absolutamente tiene que ver con mi mente lo que está fuera de ella. Mantente en esta disposición y todo te irá bien.",
    author: "Marco Aurelio",
    work: "Meditaciones",
    locator: "7.2",
    source: {
      translator: "Jacinto Díaz de Miranda",
      edition: "Soliloquios o reflexiones morales del emperador Marco Aurelio, in Obras de los moralistas griegos, Biblioteca Clásica CXVII, Madrid, Viuda de Hernando y Ca.",
      year: 1888,
      url: "https://archive.org/details/marcusaurelius_obrasdelosmoralistasgriegos_1888",
    },
  },
];
